### ISSUE TITLE
[FeatureRequest] in GFA, read sequence length from the LN tag

### ISSUE THREAD

**Issue by lh3** [rrwick/Bandage#13]
Bandage has been great with a few GFA graphs. Nonetheless, there is a small inconvenience in my case. My graphs don't contain sequences, but instead write the contig lengths to the `LN:i:` tag on the segment lines. For now, Bandage ignores the LN tag and considers all contigs to be 1bp. It would be good to recognize the LN tag. Thanks in advance.

**Comment by rrwick** [comment]
Okay, I've updated the Bandage code to look for the LN tag and use that for the node length preferentially over the sequence length.  This change is in the development branch of Bandage, so if you want to try it immediately, you can build from source using that branch.  Otherwise, assuming everything checks out, it should make its way into the next release.

I should add, however, that I may have been running on the assumption that a node's length is equal to the length of its sequence.  So I fear this could result in strange behaviour or crashes when these two values are not the same.  I'll see if I can find any issues.

**Comment by lh3** [comment]
Thanks for the quick response. In GFA, sequence can be a star "*", indicating the sequence is not available. You can take "LN" in this case. When both sequence and LN are present, you may ignore LN and trust the sequence length, or throw an error/warning if LN is conflictive.

**Comment by rrwick** [comment]
Ah, I had forgotten about that.  I've now done a couple more additions (again to the development branch), which take the star into account.

Here's the current behaviour: if the sequence is a star or totally blank, Bandage looks to the LN tag for length.  Otherwise, it uses the sequence length.

When saving a graph to file, Bandage will use the star for contigs with missing sequences.  But when you are extracting a sequence out of the graph (e.g. as part of a path), it will fill in missing sequences with the appropriate number of Ns.

**Comment by lh3** [comment]
Sound great. I am closing this issue. Thanks a lot.
