### ISSUE TITLE
Scale bar for figures generated via command line

### ISSUE THREAD

**Issue by nickp60** [rrwick/Bandage#27]
Hi Ryan,
Thanks for this great tool! This is more of a feature request than an issue. I was wondering how difficult it would be to draw a scale bar in the graphs exported from Bandage. This would be really useful comparing multiple assemblies, where the zoom level is changing dependent on the drawn orientation of the visualization. It doesn't have to be fancy, just a solid bar depicting the length of say 10kb. Is there a setting I am missing? How difficult would this be?

**Comment by rrwick** [comment]
Nick,

I don't think that would be hard to implement, though I haven't tried. My main concern is that a scale bar might give users a false degree of certainty in sequence lengths, because the visible length of a segment in Bandage and the length of the sequence do not precisely correspond.

This is because the [graph layout algorithm Bandage uses](http://www.ogdf.net/doku.php/tech:howto:frcl) is force-directed and not exact. When a graph is simple and there aren't too many edges, the relationship between visible length and sequence length is probably pretty tight. But when the graph gets tangled up with many edges, the layout algorithm has to make a lot of compromises.

Furthermore, there is a minimum node length setting (which you can adjust) that prevents nodes from getting too small. That means that all nodes below a certain sequence length end up about the same visible length.

Here's a screenshot to illustrate. I've zoomed into some short segments in a bacterial assembly graph. Some of these node have reached the minimum length, so the 6469 bp node is not 5 x the visible length of the 1310 bp node. And due to the particulars of this graph layout, the 444 bp node ended up longer than the 803 bp nodes.
![screen shot 2016-07-20 at 2 05 40 pm](https://cloud.githubusercontent.com/assets/7053555/16974742/13857c86-4e83-11e6-85b6-fbc35c93c466.png)

So while a scale bar is possible, I fear it would be confusing. Thoughts?

**Comment by nickp60** [comment]
Hi Ryan,
Thanks for your reply; I see the issue with that now, and completely agree that a scale bar would be misleading. I still think it would be valuable to have an option for a visual summary, especially when using Bandage to assess different assembly schemes. As an alternative to scale bar, what about a simple graphical output like the one below?
![bandage_key](https://cloud.githubusercontent.com/assets/14367274/16978843/02061092-4e56-11e6-8701-cf79f348f8c9.png)
Where the title of the key would give the total length of all contigs submitted, and then a few metrics are plotted as percentages. Orphaned contigs to show the percentage of contigs not included in the main graph, length_of_longest/shortest_possible_ seq would be the length of the possible contiguous edges including all the contigs above, say, the N75 (ie, in you example, the longest_possible_seq would be traced from (R->L) teal-red/yellow-green-tan-brown, and the shortest_possible_seq would be traced teal-red/yellow-green-blue-brown).  These metrics are just brainstorming, there are probably better options.  What do you think?

**Comment by rrwick** [comment]
Nick,

There are some graph statistics available in Bandage. If you click the 'More info' button at the top left of the UI, this window pops up:
<img width="851" alt="info" src="https://cloud.githubusercontent.com/assets/7053555/17281572/dc33f224-57df-11e6-82c7-8b9cfedb4b3a.png">

The value at the bottom right, 'Total length orphaned nodes', is a new addition based on your suggestion. Thanks! I also just added the percentage after the largest component length. Those additions in the [development branch](https://github.com/rrwick/Bandage/tree/development), but should be in the next release I make.

And to be clear, I'm defining an orphaned node as a node with no edges at all. So this one is orphaned: <img width="49" alt="orphaned" src="https://cloud.githubusercontent.com/assets/7053555/17281364/1a6221de-57df-11e6-9acd-2e41e3ae43be.png">
But this one is not: <img width="64" alt="not_orphaned" src="https://cloud.githubusercontent.com/assets/7053555/17281366/24da771a-57df-11e6-9430-b7e24174ea0f.png">

Your suggestion of longest/shortest possible sequences is a bit more complex. Take this graph for example:
<img width="288" alt="screen shot 2016-08-01 at 12 13 50 pm" src="https://cloud.githubusercontent.com/assets/7053555/17281747/7812c73c-57e1-11e6-85f6-b121aee3ad57.png">

What's the longest possible sequence? Skipping the loop (30 bp)? Going through the loop once (50 bp)? Going through the loop twice (70 bp)? To avoid this kind of issue, I think I'm happy to leave it as is - just showing the size of the largest connected component - and not worry about possible path lengths.

Also on my to-do list is to show the distribution of the graph's size per depth, probably as a histogram. I think that might be useful for spotting contamination and mixed samples. But that would be a bit more work and so I haven't done it yet! But if you have any more suggestions for useful statistics, do let me know. Thanks again!
