### ISSUE TITLE
Cannot save edited .fastg file into .gfa format when using Bandage on Windows and Ubuntu

### ISSUE THREAD

**Issue by danielyao12** [rrwick/Bandage#28]
Hi Ryan,
Thanks for your exited Bandage! It is really helpful when the first time someone shown me on a Mac system. But the problem is that I cannot use the function 'Save visible graph to GFA' on Windows or Ubuntu. I tried on four different computers including 32 bit and 64 bit of Windows 7 and Windows 10, and Ubuntu 14. Every time when I edited the graph, 'Merge all possible nodes', 'Save visible graph to GFA' and re-load the saved GFA file, the graph is just what it original is and cannot save what I edited. So I cannot output the sequence as one complete genome. While, the same data can be well edited in a Mac system. I do read all information in yoru website, but still cannot figure out how deal with this problem. Do you know what possible the reason is and what should I do?
Besides, I tried the version 0.7.1, but the the total length of my contigs reading in is shorter than it should be.  It seems the nodes length are incorrect. However, the version 0.7.1 can save the edited fastg file into gfa file using ‘Save visible graph to GFA'.

**Comment by rrwick** [comment]
That was a nasty bug - thanks for spotting it! I think I've fixed it now in the [development](https://github.com/rrwick/Bandage/tree/development) branch of Bandage. The fix will eventually make it into the next release and the master branch, but for now you'll need to build from source (from [development](https://github.com/rrwick/Bandage/tree/development)) to get the fix.

The issue was that Bandage tracks which nodes are 'visible' and which aren't. When nodes were merged, it was failing to remember that they are visible. So when you chose to save the visible part of the graph to the GFA, the merged nodes were excluded from the output. I'm not sure why it would work on the Mac version though - I'd expect the same behaviour on all platforms...

Anyway - give it a try now and let me know if anything's still wrong. And thanks again for finding this bug!

**Comment by danielyao12** [comment]
Thanks, Ryan! I tried to install the Bandage in the development branch this whole afternoon, but it seems my ubuntu system sill cannot use the Qt5 and cannot install the fixed source file. I'm waiting for the pre-build version update. Hopefully, it won't be too late.

**Comment by rrwick** [comment]
For what it's worth, I've found that the easiest way to build Bandage is usually through the Qt SDK ([download from here](https://www.qt.io/download-open-source/)). Then you can open the Bandage project in Qt Creator and build it from there. That's often easier than trying making your package manager get a current version of Qt so you can qmake/make from the command line.

But regardless, I'll try to push out a minor Bandage release soon!

**Comment by danielyao12** [comment]
Thank you for your help! But there are still two errors warned when I use the Qt SDK to compile the source file on ubuntu. So, I'm waiting for your updates of the pre-build version.
