### ISSUE TITLE
bandage_temp-#### files not removed after use

### ISSUE THREAD

**Issue by rec3141** [rrwick/Bandage#32]
...during command line usage of blast on MacOSX.

It's not clear whether the blast databases can be recognized and re-used. In my case I wouldn't mind keeping them around since I'm BLASTing multiple assemblies against multiple reference genomes. But if they are not re-used it makes more sense to delete them or generate them in a tmp folder where they will be auto-cleaned up.

an example invocation:
Bandage reduce assembly_graph.fastg output.gfa --scope aroundblast --distance 10 --query blastfile.fna --evfilter 1e-100

**Comment by rrwick** [comment]
No, Bandage isn't clever enough to reuse those files. Since BLAST databases are usually quick to generate, it just remakes them each time. So this is indeed a bug!

It was actually a very easy fix (https://github.com/rrwick/Bandage/commit/f360436d235083e91ce8533ecc24190c6584347d), so I've already done it and put the change (along with a couple other recent fixes) in Bandage's master branch. So if you clone from GitHub and [build a fresh copy](https://github.com/rrwick/Bandage#building-from-source), it should work! The fix will of course also be included in the next Bandage release, somewhere down the line.

Thanks for spotting this one and letting me know!
