### ISSUE TITLE
Arrowheads on edges

### ISSUE THREAD

**Issue by isovic** [rrwick/Bandage#91]
Assembly graphs are directed, and in a large number of cases (especially when debugging) it would help to see the flow of the paths in the graph by observing the direction of the edges.

Would it be possible to add this feature?

I'm aware of the option which can show the direction of a particular node, but that doesn't really depict the directionality of the paths (each read can be used in an arbitrary direction in the graph).

Best regards,
Ivan.

**Comment by rrwick** [comment]
This option is available in the settings menu: turn on 'Arrowheads in single node style'. Note that this is only meaningful information for some assembly graphs, though. E.g. positive/negative nodes don't really mean anything in SPAdes graphs, which is why it's off by default. 

And if you really want to see the full complexity of the graph, turn on double style (in the main window) to see each node in both directions with arrowheads.

Ryan
